# all:
#   vars:
#     ansible_user: hanz
#     ansible_ssh_private_key_file: "/Users/hanz/.ssh/id_ed25519"

debian_servers:
  hosts:
    alix:
      ansible_host: alix.taildad3c.ts.net
    bworm:
      ansible_host: bworm.taildad3c.ts.net
    # code:
    #   ansible_host: code.taildad3c.ts.net
    east:
      ansible_host: east.taildad3c.ts.net
  vars:
    ansible_python_interpreter: /usr/bin/python3

